### ISSUE TITLE
Shared class \"account\" has no method handling GET /

### ISSUE THREAD

**Issue by guiwunsch** [strongloop/loopback-example-database#2]
I'm trying to run this demo but is showing this error:

Browser error:
{
"error": {
"name": "Error",
"status": 404,
"message": "Shared class \"account\" has no method handling GET /",
"statusCode": 404,
"stack": "Error: Shared class \"account\" has no method handling GET /\n at Object.restRemoteMethodNotFound as handle\n at next (/Users/guiwunsch/Projetos/HereIAmWS/tests/loopback-mysql-example/node_modules/loopback/node_modules/strong-remoting/node_modules/express/node_modules/connect/lib/proto.js:193:15)\n at Object.expressInit as handle\n at next (/Users/guiwunsch/Projetos/HereIAmWS/tests/loopback-mysql-example/node_modules/loopback/node_modules/strong-remoting/node_modules/express/node_modules/connect/lib/proto.js:193:15)\n at Object.query as handle\n at next (/Users/guiwunsch/Projetos/HereIAmWS/tests/loopback-mysql-example/node_modules/loopback/node_modules/strong-remoting/node_modules/express/node_modules/connect/lib/proto.js:193:15)\n at Function.app.handle (/Users/guiwunsch/Projetos/HereIAmWS/tests/loopback-mysql-example/node_modules/loopback/node_modules/strong-remoting/node_modules/express/node_modules/connect/lib/proto.js:201:3)\n at Object.fn as handle\n at next (/Users/guiwunsch/Projetos/HereIAmWS/tests/loopback-mysql-example/node_modules/loopback/node_modules/strong-remoting/node_modules/express/node_modules/connect/lib/proto.js:193:15)\n at next (/Users/guiwunsch/Projetos/HereIAmWS/tests/loopback-mysql-example/node_modules/loopback/node_modules/strong-remoting/node_modules/express/node_modules/connect/lib/proto.js:168:78)"
}
}

Terminal Log:
GET /api/accounts/ 404 3ms - 2.17kb

Can you help me?
Thanks

**Comment by nargiskhatoon** [comment]
Hi @raymondfeng I encountered the same issue. I am using "loopback-datasource-juggler": "^2.7.0", I post question but not got response, _Please visit link_, http://stackoverflow.com/questions/35643874/cannot-get-specific-file-from-s3-using-strongloop

me waiting for kind response,  Thanks

**Comment by superkhau** [comment]
@nargiskhatoon Please open a new issue with the steps to reproduce and I'll see if we can get you some help there.
