### ISSUE TITLE
lastModifiedAt doesn't get updated

### ISSUE THREAD

**Issue by ismail-s** [strongloop/loopback-example-database#24]
The models have a lastModifiedAt field, but I can't see any code that updates this field when a row is updated.

**Comment by superkhau** [comment]
It only gets updated when you go through the auto-migration process in this demo. However, I like your idea of adding an example of how you would do it normally. Merged and thanks for the contribution! ;)

**Comment by ismail-s** [comment]
Quick response. You may recognise the code, it is basically from the [docs](https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-beforesave)
