### ISSUE TITLE
Ctrl + C does not terminate the process

### ISSUE THREAD

**Issue by dnguyenv** [strongloop/loopback-example-database#26]
Hi,
While trying this loopback-exemple-database application, when I hit Ctrl + C, the app looks like terminated but it is not. The process does not get killed and I have to kill it manually. Any idea please?

Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
connectors:oracle is licensed from 2016-01-23T16:19:03.823Z to 2017-01-22T16:19:03.823Z.
^C
<dnmac>:loopback-example-database dn$ lsof -i tcp:3000
COMMAND   PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    88062 dn   24u  IPv4 0x2e934247acaae9b5      0t0  TCP *:hbci (LISTEN)

Environment:
Mac 10.10.5
Node 4.2.2

**Comment by superkhau** [comment]
Strange, I haven't run into this. Are you still running into this issue?

**Comment by mkmpvtltd1** [comment]
ya it happened to my setup too
