### ISSUE TITLE
One issue in your destination site 

### ISSUE THREAD

**Issue by mjza** [strongloop/loopback-example-database#70]
fix the connector name from `"connector": "mongodb",` to mysql in the following address:

https://loopback.io/doc/en/lb2/Connecting-to-MySQL.html

I couldn't find any link there for connection.

**Comment by dhmlau** [comment]
@mjza, sorry about the late reply.  Would you be interested in submitting a PR?  
In case you're not familiar with our contribution process, please see our `contributing to docs` page as reference: https://loopback.io/doc/en/contrib/doc-contrib.html.

**Comment by mjza** [comment]
I think I made a pull request. Sorry I am busy and cannot take time to read that and also at the moment I don't work on that project anymore. If I had some mistakes in my pull requests please fix it. Anyway I resolved the issue and you can fix it yourself.

**Comment by dhmlau** [comment]
Hi @mjza, hm.. I don't see your PR. I'm looking at https://github.com/strongloop/loopback-example-database/pulls.

**Comment by godartm** [comment]
Hi , i can take this issue if you want @dhmlau

**Comment by dhmlau** [comment]
@godartm , that would be perfect. thanks!

**Comment by godartm** [comment]
@dhmlau i have make a pull request can you verify please if i did it right ?

**Comment by dhmlau** [comment]
@godartm, sorry about the late reply.  I've commented on the PR. Thanks.

**Comment by dhmlau** [comment]
Closing as resolved. PR https://github.com/strongloop/loopback-example-database/pull/75
